#!/bin/bash
set -e
set -x

EXEC_DIR=$1

if [[ $EUID > 0 ]]; then
	echo "Run as root!";
	exit 1;
fi

CURRENT_DIR=$(pwd)
TMP=$(mktemp -d -t tmp.XXXXXXXXXX)
SRC=${TMP}/src
build_deps="
  g++ make expat libexpat1-dev liblz4-dev libfcgi-dev zlib1g-dev libevent-dev libbz2-dev libicu-dev
  curl wget autotools-dev autoconf automake libtool libc6-dev bzip2"

#
#     TRAP FUNCTION
#
#
function rmTempDirectory {
	rm -rf ${TMP}
}
trap rmTempDirectory EXIT

if [ -d ${TMP} ]; then
	echo "Directory already exists! It is a temporary directory and should not exist yet."
	exit -1;
else
	git clone -b test758_lz4hash --recurse-submodules --recursive --single-branch https://github.com/mmd-osm/Overpass-API.git ${TMP}
fi

if [ ! -d ${SRC} ]; then
	echo "Source directory does not exist!"
	exit -1;
fi

cd ${SRC}
chmod u+x test-bin/*.sh

echo exit 101 > /usr/sbin/policy-rc.d
chmod +x /usr/sbin/policy-rc.d

apt-get update
apt-get install -y ${build_deps} fcgiwrap nginx

autoscan
aclocal
autoheader
libtoolize
automake --add-missing
autoconf

cd ..

mkdir -p build
cd build
../src/configure CXXFLAGS="-std=c++11 -O2 -I../src/third_party/libosmium/include -I../src/third_party/protozero/include" LDFLAGS="-lpthread -lbz2 -levent -licuuc -licui18n" --prefix=$EXEC_DIR --enable-lz4 --enable-fastcgi --enable-tests

make V=0 install -j3

cd ../..

apt-get purge -y --auto-remove ${build_deps}
rm -rf ${TMP}

echo "Finished!"